### ISSUE TITLE
fail to build

### ISSUE THREAD

**Issue by ghost** [marocchino/StackTimer#1]
I ran the code but it does not compile. The error says:

> 2012-06-08 12:08:34.239 StackTimer[1239:707] Unable to load nib file: MainMenu, exiting

I will figure out this issue.

**Comment by ghost** [comment]
This issue can be resolved by the following actions:
1. Open project setting.
2. Click StackTimer in the targets section.
3. Change the **value** of key 'Main nib file base name', to 'StackTimerDocument'

**Comment by marocchino** [comment]
fix it.
